# Generated by Django 4.1 on 2023-08-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_bakery_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery',
            name='juice',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='doctors',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
