# Generated by Django 4.1 on 2023-08-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_bakery_juice_alter_hospital_doctors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Bakery',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
